### PR TITLE
Feature/new side bar

### PR DESCRIPTION
**Pull request by mehul1011**
Covers: #9 #6 
For your reference: 

When we implement the new chat feature and have a good number of new chats shown on the sidebar, it will be having scroll. 
Chat is very responsive now.

Flaw: On small screens, it's not opening the sidebar because I have the default set as hidden and enable it with md:w-[260px], so md & large have a sidebar, and if we open the console of the browser and pull towards a small screen, it would be hidden and hamburger would come up when clicked it won't show the sidenav since it's not to be enabled in smaller screens.

From my end, i am thinking about it how to do it easily.

I think when the screen size is small i have to take care of this separately

I have changed colors let me know if this was the one your were talking about before just that its dark mode.

Screenshot 2023-04-07 at 11 21 54 PM

### CODE REVIEW

**Comment by yagizhanNY** [comment]
Hi @mehul1011, side bar is looks great but in my opinion it can be seen much better. For example, we can change X button with menu button and give some style to `source code` button (it would be nice if it is similar with navbar button).

I am checking the pipeline fails.

**Comment by mehul1011** [comment]
> Hi @mehul1011, side bar is looks great but in my opinion it can be seen much better. For example, we can change X button with menu button and give some style to `source code` button (it would be nice if it is similar with navbar button).
> 
> I am checking the pipeline fails.  

Yes, sure @yagizhanNY 

It will be my next step for sidebar.

**Comment by yagizhanNY** [comment]
I have busy days by the way :) I will review all of the changed as soon as I can :) @mehul1011

**Comment by mehul1011** [comment]
> I have busy days by the way :) I will review all of the changed as soon as I can :) @mehul1011 

Sure not an issue i understand. Thanks

**Comment by yagizhanNY** [comment]
image

image

image

What do you think about this design? I used 3rd party tailwind library named `Flowbite`. It is works fine.

**Comment by mehul1011** [comment]
@yagizhanNY This is great, i was expecting to do like this.
So if they have to close the sidebar they can click outside and it would work?

If so we can put up these changes.

**Comment by mehul1011** [comment]
For the desktop screen we can let the chat area take full width, this would make UX better.

**Comment by mehul1011** [comment]
> For the desktop screen we can let the chat area take full width, this would make UX better.

Hi @yagizhanNY, please see if you can check the pipeline, let's merge the changes so that we are in sync with what we have, and decide on the next step.
Thanks

**Comment by yagizhanNY** [comment]
> > For the desktop screen we can let the chat area take full width, this would make UX better.
> 
> Hi @yagizhanNY, please see if you can check the pipeline, let's merge the changes so that we are in sync with what we have, and decide on the next step. Thanks

Hi @mehul1011, did you think about to use `Flowbite`? Could you change your sidebar with this library's? It's looks great and functional. Then we can merge this request.

**Comment by yagizhanNY** [comment]
> @yagizhanNY This is great, i was expecting to do like this. So if they have to close the sidebar they can click outside and it would work?
> 
> If so we can put up these changes.

Yes, it's working like that.

**Comment by mehul1011** [comment]
> > @yagizhanNY This is great, i was expecting to do like this. So if they have to close the sidebar they can click outside and it would work?
> > 
> > If so we can put up these changes.
> 
> Yes, it's working like that.

Pipeline is working correctly?

**Comment by mehul1011** [comment]
> > @yagizhanNY This is great, i was expecting to do like this. So if they have to close the sidebar they can click outside and it would work?
> > 
> > If so we can put up these changes.
> 
> Yes, it's working like that.

Pipeline is working correctly?

**Comment by mehul1011** [comment]
> > > For the desktop screen we can let the chat area take full width, this would make UX better.
> > 
> > Hi @yagizhanNY, please see if you can check the pipeline, let's merge the changes so that we are in sync with what we have, and decide on the next step. Thanks
> 
> Hi @mehul1011, did you think about to use `Flowbite`? Could you change your sidebar with this library's? It's looks great and functional. Then we can merge this request.

Sure i will get a look at this. 
Thanks for suggesting.

**Comment by yagizhanNY** [comment]
> > > @yagizhanNY This is great, i was expecting to do like this. So if they have to close the sidebar they can click outside and it would work?
> > > If so we can put up these changes.
> > 
> > 
> > Yes, it's working like that.
> 
> Pipeline is working correctly?

Yes, it worked correctly when I run it.

**Comment by mehul1011** [comment]
> > > > For the desktop screen we can let the chat area take full width, this would make UX better.
> > > 
> > > 
> > > Hi @yagizhanNY, please see if you can check the pipeline, let's merge the changes so that we are in sync with what we have, and decide on the next step. Thanks
> > 
> > 
> > Hi @mehul1011, did you think about using `Flowbite`? Could you change your sidebar with this library's? It looks great and functional. Then we can merge this request.
> 
> Sure i will get a look at this. Thanks for suggesting it.

Hi @yagizhanNY, i check flowbite with angular, doesn't seem to have proper documentation for angular, can you please suggest me some

Currently, i have flowbite sidebar done, but the button toggle to show and hide is not working since i wanted to see how to make the boilerplate code work, like how it's done in html boilerplate code that i copied from flowbite site.

I will push the updated code if you need it, just needed little help, i can just keep a property like showSideBar on the parent tag, but it's still not showing full content, when we are supposed to show the sidebar.

**Comment by yagizhanNY** [comment]
> > > > > For the desktop screen we can let the chat area take full width, this would make UX better.
> > > > 
> > > > 
> > > > Hi @yagizhanNY, please see if you can check the pipeline, let's merge the changes so that we are in sync with what we have, and decide on the next step. Thanks
> > > 
> > > 
> > > Hi @mehul1011, did you think about using `Flowbite`? Could you change your sidebar with this library's? It looks great and functional. Then we can merge this request.
> > 
> > 
> > Sure i will get a look at this. Thanks for suggesting it.
> 
> Hi @yagizhanNY, i check flowbite with angular, doesn't seem to have proper documentation for angular, can you please suggest me some
> 
> Currently, i have flowbite sidebar done, but the button toggle to show and hide is not working since i wanted to see how to make the boilerplate code work, like how it's done in html boilerplate code that i copied from flowbite site.
> 
> I will push the updated code if you need it, just needed little help, i can just keep a property like showSideBar on the parent tag, but it's still not showing full content, when we are supposed to show the sidebar.

Hello @mehul1011, did you follow the installation [steps](https://flowbite.com/docs/getting-started/quickstart/)? This functionality is working automatically when the Flowbite's js files are imported successfully. Could you check this once more?

**Comment by mehul1011** [comment]
> > > > > > For the desktop screen we can let the chat area take full width, this would make UX better.
> > > > > 
> > > > > 
> > > > > Hi @yagizhanNY, please see if you can check the pipeline, let's merge the changes so that we are in sync with what we have, and decide on the next step. Thanks
> > > > 
> > > > 
> > > > Hi @mehul1011, did you think about using `Flowbite`? Could you change your sidebar with this library's? It looks great and functional. Then we can merge this request.
> > > 
> > > 
> > > Sure i will get a look at this. Thanks for suggesting it.
> > 
> > Hi @yagizhanNY, i check flowbite with angular, doesn't seem to have proper documentation for angular, can you please suggest me some
> > 
> > Currently, i have flowbite sidebar done, but the button toggle to show and hide is not working since i wanted to see how to make the boilerplate code work, like how it's done in html boilerplate code that i copied from flowbite site.
> > 
> > I will push the updated code if you need it, just needed little help, i can just keep a property like showSideBar on the parent tag, but it's still not showing full content, when we are supposed to show the sidebar.
> 
> Hello @mehul1011, did you follow the installation [steps](https://flowbite.com/docs/getting-started/quickstart/)? This functionality is working automatically when the Flowbite's js files are imported successfully. Could you check this once more?

Hi @yagizhanNY , thanks for the reference. I will check with this again.

**Comment by mehul1011** [comment]
Hi @yagizhanNY, with flowbite it's done (let's merge this and quickly move forward to implementing multiple chats)

I have opened #14 issue, please have a look.

**Comment by yagizhanNY** [comment]
@mehul1011 it merged but I guess you have forgot `flowbite` dependency in `package.json` file. I added and push the code to the master branch. Please pull the last changes.

**Comment by mehul1011** [comment]
> @mehul1011 it merged but I guess you have forgot `flowbite` dependency in `package.json` file. I added and push the code to the master branch. Please pull the last changes.

Thanks a lot @yagizhanNY, i had some branch issues, things may have messed up there.

**Pull request merged**
